name: Test GCP Auth
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          token_format: access_token
      
      - name: Test Registry Access
        run: |
          curl -H "Authorization: Bearer ${{ steps.auth.outputs.access_token }}" \
            https://us-central1-docker.pkg.dev/v2/wide-ratio-423022-e8/smart-erp-api/tags/list
